version: '3.4'
services:
  web:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/opt/app
      
  db:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_USER: "gwcmk"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "gwcmk-library-app"
